### ISSUE TITLE
The module 'PublishCoverity' could not be loaded.

### ISSUE THREAD

**Issue by Mailaender** [csMACnz/coveritypublisher#13]
Looks like version 0.11.0 is broken. See https://ci.appveyor.com/project/OpenRA/openra/build/1.0.5551#L450

**Comment by csMACnz** [comment]
Sorry, there is a breaking change, i had to move it into the tools folder otherwise it would not work correctly with 2015.

```
 PublishCoverity\tools\PublishCoverity.exe compress ...
```
