### ISSUE TITLE
The page you were looking for doesn't exist (404)

### ISSUE THREAD

**Issue by Mailaender** [csMACnz/coveritypublisher#15]
I guess there is another issue with version 0.11 during upload:
https://ci.appveyor.com/project/OpenRA/openra/build/1.0.5590#L528

**Comment by csMACnz** [comment]
Unfortunately, thats not me, and is still broken in 0.10.0.  Something changed on coverity's side 2 days ago. I'm investigating the problem and looking for a solution now.

Working build with 0.10.0
https://ci.appveyor.com/project/MarkClearwater/bclextensions/build/1.2.0-unstable.56%20(Build%20349)
Failing build on the same commit a day later:
https://ci.appveyor.com/project/MarkClearwater/bclextensions/build/1.2.0-unstable.56%20(Build%20350)

**Comment by csMACnz** [comment]
**Update**: the UI upload works. It seems to just be the "https://scan.coverity.com/builds"  endpoint that has started failing. Even using it from curl at the command line gives me the same 404 response. Trying to sign up to the forum to raise the issue, waiting for the manual verification step.

Looks like most other scripts use http://scan5.coverity.com/cgi-bin/upload.py. This is only http but has been the way scripts have been doing it for several years now.  not sure if https://scan.coverity.com/builds is newer and better or if i should change. Pretty simple change to make though. And the scan5 one does work from command line.

**Comment by csMACnz** [comment]
This all seems to be working again for me today the scan5 api seems slower so I wan't be switching to it. Ill close the ticket for now. Re-open if the issue comes back.

**Comment by Mailaender** [comment]
Yay, the https://scan.coverity.com/projects/3650 passed again. Thanks!
