### ISSUE TITLE
Add `--nologo` option to `compress` command.

### ISSUE THREAD

**Issue by psfrolov** [csMACnz/coveritypublisher#3]

**Comment by csMACnz** [comment]
Thanks for the feedback, already added this to develop so will be there in the next release:
https://github.com/csMACnz/coveritypublisher/blob/develop/src/csmacnz.CoverityPublisher/Main.usage.txt

**Comment by csMACnz** [comment]
Release version 0.10.0 is published with these changes: https://www.nuget.org/packages/PublishCoverity
