### ISSUE TITLE
Any ideas on why my publish is failing

### ISSUE THREAD

**Issue by gep13** [csMACnz/coveritypublisher#4]
https://ci.appveyor.com/project/GaryEwanPark/githubreleasemanager/build/0.1.0-unstable.54%20(Build%2017)#L374

I haven't dug into it yet, and this is the first time that I have tried the upload, so likely I am doing something wrong, but just wanted to ask for any obvious troubleshooting tips.

Thanks

**Comment by gep13** [comment]
As an update...

I have just tried running the same command locally on my machine, with all the variables populated, and I get the same "Not Found" error.  It seems as though there is a delay, while it is uploading the file, and then it returns the error message.

Any ideas?

Thanks!

**Comment by gep13** [comment]
Ok, I have found the issue, although I am not sure why I would have to do this, as it is surely working for you...

I was trying to use the argument `-r gep13/GitHubReleaseManager` but this wasn't working.  I have just downloaded the source code for this project, and removed the requirement of the repository name to contain a slash, and I have instead used `-r GitHubReleaseManager` and this works without any issues.  The zip file is uploaded, and the build sent to the queue.

Do you have any ideas as to why you would require to use the full name of the repository, including your username, and I don't?

When I check my dashboard, this is what I see:

![image](https://cloud.githubusercontent.com/assets/1271146/6676697/d09fc82a-cc21-11e4-9036-e68133b06f08.png)

Which led me to try with a non qualified repository name.

Cheers!

**Comment by csMACnz** [comment]
Thanks @gep13 for letting me know. I'll do some more investigation into why they are different but looks like I just need to remove any constraints on the name.
I think I need to do some work to make it clearer what the reasons for failure are too.

**Comment by gep13** [comment]
Yip, that is essentially what I did in my local version.  Removed the if statement around there being a / in the repo name.

Let me know if you want me to check anything, looking forward to your next release!

**Comment by csMACnz** [comment]
Release version 0.10.0 is published with these changes: https://www.nuget.org/packages/PublishCoverity
